baseURL = "https://wesleywilde.netlify.app"
disableLanguages = []
disqusShortname = " wesleywilde"
googleAnalytics = "G-9G6X7L8C40"
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "My Autistic Life"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Wesley Wilde"
description = "My Autistic Life"
[params.banner]
heading = "My Autistic Life"
image = ""
[params.blog]
heading = "Latest Articles"
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Feel free to email me at info@myaustisticlife.co if you're interested in sharing your experience or wish to connect more as this information is resonating deeply with you. Regardless, I'm happy to help!"
enable = true
title = "Contact me for more information."
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = ""
content = "👋 I'm Wesley Wilde. I'm a nonbinary autistic artist and musician. It's nice to meet you!"
copyright = "Copyright &copy; 2021 — Made with ❤️ in Seattle, WA"
hours = ""
title = "About Me"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
